### ISSUE TITLE
Periodic Labeler Exit Code 255 error on every run

### ISSUE THREAD

**Issue by MichalPetryka** [paulfantom/periodic-labeler#1]
We're getting this on every labeler run:
```
2019-11-28T18:45:34.3846459Z ##[command]/usr/bin/docker run --name quayiopaulfantomperiodiclabelerlatest_b10f13 --label f6cdeb --workdir /github/workspace --rm -e GITHUB_TOKEN -e GITHUB_REPOSITORY -e LABEL_MAPPINGS_FILE -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/SCPSL-Translations/SCPSL-Translations":"/github/workspace" quay.io/paulfantom/periodic-labeler:latest
2019-11-28T18:45:35.2444794Z ERROR: logging before flag.Parse: F1128 18:45:35.073126       1 main.go:96] yaml: unmarshal errors:
2019-11-28T18:45:35.2458667Z   line 1: cannot unmarshal !!str `README.md` into []string
2019-11-28T18:45:35.2459102Z   line 2: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2459327Z   line 3: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2459535Z   line 4: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2459919Z   line 5: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2460607Z   line 6: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2461018Z   line 7: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2461352Z   line 8: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2461685Z   line 9: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2462110Z   line 10: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2463788Z   line 11: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2464177Z   line 12: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2464454Z   line 13: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2464666Z   line 14: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2464868Z   line 15: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2465226Z   line 16: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2465427Z   line 17: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2465870Z   line 18: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2466085Z   line 19: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2466689Z   line 20: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2466972Z   line 21: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2467303Z   line 22: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2467543Z   line 23: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2467734Z   line 24: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2468057Z   line 25: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2468201Z   line 26: cannot unmarshal !!str `Transla...` into []string
2019-11-28T18:45:35.2468509Z goroutine 1 [running]:
2019-11-28T18:45:35.2468743Z github.com/golang/glog.stacks(0xc00000e000, 0xc00039bc00, 0x66a, 0x6bf)
2019-11-28T18:45:35.2469865Z 	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:769 +0xb8
2019-11-28T18:45:35.2470330Z github.com/golang/glog.(*loggingT).output(0x9f4480, 0xc000000003, 0xc0002bf810, 0x9ab8e7, 0x7, 0x60, 0x0)
2019-11-28T18:45:35.2471210Z 	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:720 +0x372
2019-11-28T18:45:35.2471595Z github.com/golang/glog.(*loggingT).printDepth(0x9f4480, 0x3, 0x1, 0xc000045f00, 0x1, 0x1)
2019-11-28T18:45:35.2472645Z 	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:646 +0x129
2019-11-28T18:45:35.2473074Z github.com/golang/glog.(*loggingT).print(...)
2019-11-28T18:45:35.2475637Z 	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:637
2019-11-28T18:45:35.2476210Z github.com/golang/glog.Fatal(...)
2019-11-28T18:45:35.2494402Z 	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:1128
2019-11-28T18:45:35.2494998Z main.main()
2019-11-28T18:45:35.2495639Z 	/go/src/github.com/paulfantom/periodic-labeler/main.go:96 +0x4cb
2019-11-28T18:45:35.2509372Z ##[error]Docker run failed with exit code 255
```
Our repository: https://github.com/northwood-studios/SCPSL-Translations

**Comment by MichalPetryka** [comment]
Apparently, the 2nd one from labeler example isn't supported:
```
#WORKS
# Add 'label1' to any changes within 'example' folder or any subfolders
label1:
  - example/**/*

#DOESN'T WORK
# Add 'label2' to any file changes within 'example2' folder
label2: example2/*
```

**Comment by srbarrios** [comment]
> Apparently, the 2nd one from labeler example isn't supported:
> 
> ```
> #WORKS
> # Add 'label1' to any changes within 'example' folder or any subfolders
> label1:
>   - example/**/*
> 
> #DOESN'T WORK
> # Add 'label2' to any file changes within 'example2' folder
> label2: example2/*
> ```

Hi,

In my case it works only with the second example :man_shrugging:

**Comment by paulfantom** [comment]
@srbarrios are you sure? I am personally using the first example in all @cloudalchemy repositories ([example](https://github.com/cloudalchemy/ansible-prometheus/blob/master/.github/labeler.yml)) and it works there. Also, I investigated codebase and the second example cannot possibly work in golang due to how the data structure is defined (https://github.com/paulfantom/periodic-labeler/blob/master/main.go#L93) - it expects a map of lists.

I am open to PRs fixing this issue, but personally I don't have time to add this right now.

**Comment by srbarrios** [comment]
Hi @paulfantom , here https://github.com/uyuni-project/uyuni/pull/1711/files I tried to reformat using the first example, as I thought the problem was to have the filter inline with the label, instead of having it in a new line. But then the matcher `/**/*` didn't catch any file, then I tried only with `/*` and it catched the files in the root folder but still the recursivity is not working for me.

TBH I didn't have time to play a lot with that GitHub Action. I might be still doing something wrong, looking into your commented example, it might work if I include both `/**/*` and `/*`.

I'll let you know when I have some minutes to play with it :)

Thank you!

**Comment by paulfantom** [comment]
Yeah, I didn't test `something/**/*` matchers... Could you open a separate issue about it as it is a different bug?

**Comment by srbarrios** [comment]
Ok! I will, as soon as I can reproduce exactly the problem.
I tried now in my fork.. and recursivity works fine, but it doesn't in the PRs of my upstream, it might be related to forked branches, not sure, so as soon I clarify I open an issue to discuss about it ;)
Thanks Paul.

**Comment by mehmet-erim** [comment]
Is there any news?

**Comment by ilyam8** [comment]
`/**/*` support added in #8
