### ISSUE TITLE
default config does not seem to work out of the box

### ISSUE THREAD

**Issue by maxandersen** [paulfantom/periodic-labeler#6]
I setup periodic labeler on https://github.com/maxandersen/quarkus-nonfork to try and work around action/labeler limits.

But using the default setup I end up with errors when running, see https://github.com/maxandersen/quarkus-nonfork/commit/1f9eececb01eab0fa6cb11ed36c05f7d1b0f6f71/checks?check_suite_id=409946518

```
ERROR: logging before flag.Parse: F0120 12:26:51.433401       1 main.go:85] GET https://api.github.com/repos/maxandersen/quarkus-nonfork/contents/.github/labeler.yml: 401 Bad credentials []
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc00007c000, 0xc0000cc200, 0x9c, 0xf1)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0x9f4480, 0xc000000003, 0xc0000960e0, 0x9abbcf, 0x7, 0x55, 0x0)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:720 +0x372
github.com/golang/glog.(*loggingT).printDepth(0x9f4480, 0x3, 0x1, 0xc000419ed0, 0x1, 0x1)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:646 +0x129
github.com/golang/glog.(*loggingT).print(...)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:637
github.com/golang/glog.Fatal(...)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:1128
main.main()
	/go/src/github.com/paulfantom/periodic-labeler/main.go:85 +0x33a
##[error]Docker run failed with exit code 255
```

its basically saying it does not have access which it obviously should have as it is handed the GITHUB  secret...

**Comment by maxandersen** [comment]
also now tried handing a full permission token to the job and same issue - I'm kinda lost on why it should get bad creds for this.
